env:
  node: true
  jest: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - airbnb-base
  - plugin:prettier/recommended
  - plugin:import/recommended
plugins:
  - prettier
  - jest
  - import
rules:
  prettier/prettier:
    - error
  no-console: 'off'
  consistent-return: 'off'
  no-underscore-dangle: 'off'
  func-names: 'off'
  no-else-return: 'off'
  jest/expect-expect: 'off'
